/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.util.forma;

import io.util.swing.jtable.component.JTableModel;
import io.util.swing.jtable.util.ColumnAutoSizeUtil;
import io.util.swing.jtable.util.ColumnUtil;
import io.util.swing.jtable.util.EventUtil;
import io.util.swing.jtable.util.TableUtil;
import io.util.swing.jtable.util.rendered.TableButtonCellRender;

import io.util.test.model.TestModel;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.List;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 *
 * @author fochoac
 */
public class FormaTest extends javax.swing.JFrame {

    private static final long serialVersionUID = 8150034364927655266L;
    private TestModel modeloSeleccionado;

    /**
     * Creates new form FormaTest
     */
    public FormaTest() {
        initComponents();
        List<TestModel> lista = cargarData();
        cargarEventosBotones(lista);
        tblTest.setModel(new JTableModel(lista));
        TableUtil.applyGenericTableProperties(tblTest);
        tblTest.repaint();
        ColumnAutoSizeUtil.sizeColumnsToFit(tblTest);
        tblTest.setAutoCreateRowSorter(true);
        //ColumnUtil.getInstance().setBackgroundColor(Color.yellow).setHorizontalAlignment(SwingUtilities.RIGHT).apply(tblTest, 0, 1, 2, 3, 4);
        ColumnUtil.getInstance().setBackgroundColor(Color.red).setHorizontalAlignment(SwingUtilities.RIGHT).apply(tblTest);
        TableButtonCellRender.renderedButtons(tblTest, new Integer[]{4, 5});
        tblTest.setRowHeight(25);
        tblTest.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblTest.setShowGrid(true);
        tblTest.setShowVerticalLines(true);
        tblTest.setGridColor(new Color(0, 128, 0));

    }

    private void cargarEventosBotones(List<TestModel> lista) {
        for (TestModel m : lista) {
            m.getBoton2().addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    ejecutarAccionBotonDos();
                }
            });
            m.getBoton().addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    ejecutarAccionBotonUno();
                }
            });

        }
    }

    private void ejecutarAccionBotonUno() {
        System.out.println("opt 1: " + modeloSeleccionado);
    }

    private void ejecutarAccionBotonDos() {
        System.out.println("opt 2: " + modeloSeleccionado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTest = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTest);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTestMouseClicked
        modeloSeleccionado = (TestModel) EventUtil.getObjectFromClick(evt, tblTest);
        EventUtil.executeClick(evt, tblTest);

    }//GEN-LAST:event_tblTestMouseClicked
    private List cargarData() {
        TestModel m1 = new TestModel("10", "9", "3", "4");
        TestModel m2 = new TestModel("9", "8", "3", "4");
        TestModel m3 = new TestModel("8", "7", "3", "4");
        TestModel m4 = new TestModel("7", "6", "3", "4");
        TestModel m5 = new TestModel("6", "5", "3", "4");
        TestModel m6 = new TestModel("5", "4", "3", "4");
        TestModel m7 = new TestModel("4", "3", "3", "4");
        TestModel m8 = new TestModel("3", "2", "3", "4");
        TestModel m9 = new TestModel("2", "1", "3", "4");
        TestModel m10 = new TestModel("1", "0", "3", "4");
        return Arrays.asList(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaTest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaTest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaTest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaTest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaTest().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTest;
    // End of variables declaration//GEN-END:variables
}
